<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>BgmPlayer</AssemblyName>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>player.ico</ApplicationIcon>
    <Authors>Tyler Parret True (https://github.com/OwlHowlinMornSky)</Authors>
    <Copyright>Copyright (C) 2025-2026 Tyler Parret True (OHMS)</Copyright>
    <Version>1.1.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="player.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlayerKernel\PlayerKernel.vcxproj" />
  </ItemGroup>

</Project>
